title: Security and Software Engineering Conference Info

description: 보안 분야 및 소프트웨트 공학 분야의 우수 컨퍼런스의 학술 논문 제출에 대한 카운트 다운 정보를 제공합니다. 또한 한국연구재단 BK21 플러스 사업 CS 컨퍼런스 IF에 따라 분류도 제공합니다.

english_description: We provide D-day countdown for research papers of Security and Software Engineering conferences and also includes BK21 Plus CS conferences IF.


author: Heedong Yang

domain: "https://conf.ssp.kr"
baseurl: ""

github_username: heedongy
github_repo: Sec-Conference-info

markdown: kramdown

